export const SETTING_CHOICES = 'SETTING_CHOICES';
export const SET_CHOICES_SUCCESS = 'SET_CHOICES_SUCCESS';
export const SET_CHOICES_FAIL = 'SET_CHOICES_FAIL';
export const RESET_CHOICES = 'RESET_CHOICES';

export const SETTING_ATTRIBUTES = 'SETTING_ATTRIBUTES';
export const SET_ATTRIBUTES_SUCCESS = 'SET_ATTRIBUTE_SUCCESS';
export const SET_ATTRIBUTES_FAIL = 'SET_ATTRIBUTE_FAIL';
export const RESET_ATTRIBUTES = 'RESET_ATTRIBUTES';
export const SET_ATTR_FOR_CHOICES = 'SET_ATTR_FOR_CHOICES';
