export const SETTING_CHOICES = 'SETTING_CHOICES';
export const SET_CHOICES_SUCCESS = 'SET_CHOICES_SUCCESS';
export const SET_CHOICES_FAIL = 'SET_CHOICES_FAIL';
export const RESET_CHOICES = 'RESET_CHOICES';
